[book]
title = "DotR"
authors = ["Utsob Roy"]
description = "A dotfiles manager that is as dear as a daughter."
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/uroybd/DotR"
edit-url-template = "https://github.com/uroybd/DotR/edit/main/docs/{path}"
site-url = "/"
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "frappe"

[output.html.search]
enable = true
